### PR TITLE
Added feature for locking aspect Ratio while Cropping.

### PR DESCRIPTION
**Pull request by mihirpmehta**
use
` iGRPTViewController.lockAspectRatio(isLock: true)` 

to lock the aspect ratio.
After setting this aspectRatioLocked as true, User can crop the image in given aspect ratio only.

### CODE REVIEW

**Comment by iKorich** [comment]
@mihirpmehta could you resolve conflict? 
And I'll make pull-request

**Comment by mihirpmehta** [comment]
It says "These conflict are too complex to resolve in web editor" Where can i resolve it. 
In github Desktop how to resolve this conflict ?

**Comment by iKorich** [comment]
@mihirpmehta please work and test in Xcode.
I haven't time to resolve conflicts in project

**Comment by mihirpmehta** [comment]
Sorry but i did not see any conflict in file itself. it says conflict but when i open it i see no conflict.

**Comment by iKorich** [comment]
Test

**Pull request merged**
